"""make_robot -- add the floor camera to the Phase B youbot.

Same rule as make_world.py: read the Phase B robot, write a NEW file, never
touch the original. The harvesting robot keeps its URDF exactly as it was
measured, and this project gets one with a sensor boom on it.

WHAT IS ADDED, AND WHY EACH PIECE

    boom          a bar from the mast out over the front bumper, ending at
                  x = SENSOR_OFFSET_X. This is the point that goes on the
                  cross. It exists as a visual so that what you see in
                  Gazebo is where the robot claims to be.
    floor_cam     a camera at the end of the boom looking straight DOWN.
                  Nadir, so the centre of its picture is the reference point
                  itself -- see agri/vision.py for why that matters and for
                  the sign convention it fixes.

WHY THE SENSOR IS DECLARED ON base_link

sdformat lumps links joined by FIXED joints into their parent, and drops any
sensor attached to a link that gets lumped away. The Phase B URDF carries a
comment about exactly this: its main camera had to move onto the pan head,
which hangs off a REVOLUTE joint and therefore survives. The floor camera has
no reason to move, so rather than invent a joint for it, the sensor is
declared against base_link with an explicit pose. That is the form that
works, and it is the form the original file used before the pan head existed.

WHY NOT JUST EDIT THE URDF BY HAND

Because the camera's height, field of view and forward offset appear in three
places -- the URDF, agri/vision.py's projection, and the driver that turns a
pixel offset into a velocity. Hand-editing means the day someone raises the
boom by 5 cm, two of the three change. Here the URDF is generated FROM
vision.py's constants, so there is one number and it is in Python.
"""

from __future__ import annotations

import argparse
import math
import re
from pathlib import Path

from agri.catalogue import (CAMERA_PIVOT_X, PLANT_CAM_Z,
                            SENSOR_OFFSET_X, plant_camera_frame,
                            plant_frame_span)
from agri.vision import CAM_HFOV, CAM_HEIGHT, CAM_WIDTH, CAM_X, CAM_Y, CAM_Z

#: The gz topic the camera publishes on, and therefore the name the bridge
#: and the robot node must both use. One copy.
FLOOR_CAM_TOPIC = "floor_cam"
BOOM_Z = CAM_Z + 0.07          # the bar rides ABOVE the lens, never in shot


def boom_sdf() -> str:
    """The visible boom and the downward camera, as URDF/gazebo fragments."""
    length = CAM_X - 0.22                      # from the mast to the lens
    mid = 0.22 + length / 2.0
    return f"""
  <!-- ================================================================
       SENSOR BOOM, generated by cloud_agri/agri/world/make_robot.py.
       Do not edit by hand: the numbers come from agri/vision.py and
       agri/catalogue.py, and the robot drives to those, not to these.
       ================================================================ -->
  <link name="sensor_boom">
    <inertial><mass value="0.12"/><inertia ixx="1e-4" ixy="0" ixz="0" iyy="1e-4" iyz="0" izz="1e-4"/></inertial>
    <visual><origin xyz="0 0 0"/><geometry><box size="{length:.4f} 0.035 0.02"/></geometry><material name="dark"/></visual>
  </link>
  <joint name="j_sensor_boom" type="fixed">
    <parent link="base_link"/><child link="sensor_boom"/>
    <origin xyz="{mid:.4f} 0 {BOOM_Z:.4f}"/>
  </joint>

  <link name="floor_cam">
    <inertial><mass value="0.04"/><inertia ixx="1e-5" ixy="0" ixz="0" iyy="1e-5" iyz="0" izz="1e-5"/></inertial>
    <visual><geometry><box size="0.035 0.035 0.03"/></geometry><material name="dark"/></visual>
  </link>
  <joint name="j_floor_cam" type="fixed">
    <parent link="base_link"/><child link="floor_cam"/>
    <origin xyz="{CAM_X:.4f} {CAM_Y:.4f} {CAM_Z:.4f}" rpy="0 {math.pi / 2:.6f} 0"/>
  </joint>
  <gazebo reference="floor_cam"><gravity>false</gravity></gazebo>
  <gazebo reference="sensor_boom"><gravity>false</gravity></gazebo>

  <!-- Declared on base_link with an explicit pose, NOT on floor_cam: a link
       behind a fixed joint is lumped away by sdformat and its sensor goes
       with it. rpy pitch = +pi/2 turns the camera's viewing axis from body
       +x to straight down; agri/vision.py depends on exactly this line. -->
  <gazebo reference="base_link">
    <sensor name="floor_cam" type="camera">
      <pose>{CAM_X:.4f} {CAM_Y:.4f} {CAM_Z:.4f} 0 {math.pi / 2:.6f} 0</pose>
      <topic>{FLOOR_CAM_TOPIC}</topic>
      <update_rate>10</update_rate>
      <always_on>true</always_on>
      <visualize>false</visualize>
      <camera>
        <horizontal_fov>{CAM_HFOV}</horizontal_fov>
        <image>
          <width>{CAM_WIDTH}</width>
          <height>{CAM_HEIGHT}</height>
          <format>R8G8B8</format>
        </image>
        <clip><near>0.02</near><far>3.0</far></clip>
      </camera>
      <gz_frame_id>floor_cam</gz_frame_id>
    </sensor>
  </gazebo>
"""


#: How far the pan head must be able to turn, and why Phase B's limit is
#: not enough.
#:
#: Phase B built the head for a robot that looked FORWARD at a row it was
#: driving along, so +/-90 degrees was generous. Phase C parks the chassis
#: beside the plant and photographs it side-on from a lens 0.18 m ahead of
#: base_link, which needs 108.1 degrees (see catalogue.CAMERA_LEVER_X).
#: At Phase B's limit the joint saturates at 90 and the plant sits 18
#: degrees off-centre -- in frame, so nothing looks broken.
#:
#: Widened HERE rather than in Phase B's URDF, because Phase C generates
#: its own robot and must not write into the other project. 125 degrees
#: leaves 17 degrees of margin, which a position controller at its stop
#: needs and an ordinary commercial pan unit has many times over.
PAN_LIMIT = math.radians(125.0)
_PHASE_B_PAN_LIMIT = '<limit lower="-1.5708" upper="1.5708" effort="4.0" velocity="1.5"/>'


def _widen_pan(urdf: str) -> str:
    """Give j_camera_pan the travel Phase C's geometry needs.

    Anchored on the joint block rather than on the limit string alone: the
    arm joints could one day carry the same numbers, and a blind replace
    would quietly re-limit them too.
    """
    head = urdf.find('<joint name="j_camera_pan"')
    if head < 0:
        raise ValueError("no j_camera_pan joint in the source robot")
    end = urdf.find("</joint>", head)
    block = urdf[head:end]
    if _PHASE_B_PAN_LIMIT not in block:
        raise ValueError(
            "j_camera_pan does not carry the limit this generator expects.\n"
            f"  wanted: {_PHASE_B_PAN_LIMIT}\n"
            "  The Phase B robot changed; check the new limit is at least "
            f"{math.degrees(PAN_LIMIT):.0f} deg and update PAN_LIMIT.")
    wider = (f'<limit lower="{-PAN_LIMIT:.4f}" upper="{PAN_LIMIT:.4f}" '
             'effort="4.0" velocity="1.5"/>')
    return urdf[:head] + block.replace(_PHASE_B_PAN_LIMIT, wider) + urdf[end:]


#: What Phase B's plant camera is aimed and lensed for, and what this
#: generator replaces it with. Matched exactly rather than blind-replaced,
#: so a change on the Phase B side is an error here and not a silent
#: mis-aim of all 48 photographs.
_PHASE_B_CAM_RPY = 'rpy="0 -0.28 0"'
_PHASE_B_CAM_POSE = "<pose>0.14 0 0 0 -0.28 0</pose>"
_PHASE_B_CAM_FOV = "<horizontal_fov>1.2</horizontal_fov>"


def _aim_plant_camera(urdf: str) -> tuple[str, str]:
    """Point the pan camera AT the plant, through a lens that frames it.

    Phase B aimed this camera 16 degrees up through a 68.8 degree lens,
    for crates down an aisle. On a 27 cm plant 0.64 m away that frames
    87 x 65 cm -- two thirds wall, floor and sky in every photograph. The
    replacement comes from catalogue.plant_camera_frame(), which derives
    both numbers from where the plant actually stands.

    The pose appears TWICE in the source -- once on the j_camera joint,
    once on the <sensor> that rides on camera_pan -- and they must agree or
    the picture and the tf frame disagree about where the camera points.
    Both are replaced here, and a source that does not carry both exactly
    is an error rather than a partial edit.
    """
    pitch, hfov = plant_camera_frame()

    # The mast height is a number the framing is computed FROM, so read it
    # back rather than trust it -- the same rule as the pivot x below.
    m = re.search(r'<joint name="j_camera_pan".*?<origin xyz="[-\d.]+ [-\d.]+ '
                  r'([-\d.]+)"', urdf, re.S)
    if m is None:
        raise ValueError("cannot read the j_camera_pan height from the source")
    if abs(float(m.group(1)) - PLANT_CAM_Z) > 1e-6:
        raise ValueError(
            f"the robot carries its pan head at z={m.group(1)} but "
            f"catalogue.PLANT_CAM_Z says {PLANT_CAM_Z}. The camera's pitch "
            "is computed from that height; every photograph would be aimed "
            "at the wrong part of the plant.")

    for wanted in (_PHASE_B_CAM_RPY, _PHASE_B_CAM_POSE, _PHASE_B_CAM_FOV):
        if wanted not in urdf:
            raise ValueError(
                f"the Phase B robot no longer carries {wanted!r}. It was "
                "aimed and lensed for crates; Phase C re-aims it at a "
                "plant. Check what changed before updating this matcher.")

    urdf = urdf.replace(_PHASE_B_CAM_RPY, f'rpy="0 {pitch:.6f} 0"')
    urdf = urdf.replace(_PHASE_B_CAM_POSE,
                        f"<pose>0.14 0 0 0 {pitch:.6f} 0</pose>")
    urdf = urdf.replace(_PHASE_B_CAM_FOV,
                        f"<horizontal_fov>{hfov:.6f}</horizontal_fov>")

    fb, pb, pt, ft = plant_frame_span()
    note = (f"plant camera re-aimed {math.degrees(-pitch):+.1f} deg "
            f"(was +16.0), lens {math.degrees(hfov):.1f} deg (was 68.8)\n"
            f"  the plant spans {math.degrees(pb):+.1f} to "
            f"{math.degrees(pt):+.1f} deg in a frame of "
            f"{math.degrees(fb):+.1f} to {math.degrees(ft):+.1f} -- "
            f"{math.degrees(pb - fb):.1f} deg of margin below, "
            f"{math.degrees(ft - pt):.1f} above")
    return urdf, note


def build(source: Path, target: Path) -> str:
    urdf = source.read_text()
    if "</robot>" not in urdf:
        raise ValueError(f"{source} has no </robot> to insert before")
    if "floor_cam" in urdf:
        raise ValueError(f"{source} already has the boom; generate from the "
                         "ORIGINAL Phase B robot, not from a generated one")

    # The pan mast's position is a number Phase C reasons about (it is what
    # CAMERA_LEVER_X is measured from), so read it back rather than trust
    # it. A silent disagreement here aims every photograph slightly wrong.
    m = re.search(r'<joint name="j_camera_pan".*?<origin xyz="([-\d.]+) ',
                  urdf, re.S)
    if m is None:
        raise ValueError("cannot read the j_camera_pan origin from the source")
    if abs(float(m.group(1)) - CAMERA_PIVOT_X) > 1e-6:
        raise ValueError(
            f"the robot mounts its pan head at x={m.group(1)} but "
            f"catalogue.CAMERA_PIVOT_X says {CAMERA_PIVOT_X}. Every plant "
            "photograph is aimed from that number; fix the catalogue.")

    urdf = _widen_pan(urdf)
    urdf, aim = _aim_plant_camera(urdf)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(urdf.replace("</robot>", boom_sdf() + "</robot>", 1))

    half_x = CAM_Z * math.tan(CAM_HFOV / 2.0) * CAM_HEIGHT / CAM_WIDTH
    half_y = CAM_Z * math.tan(CAM_HFOV / 2.0)
    return "\n".join([
        f"floor camera written to {target}",
        f"  reference point {SENSOR_OFFSET_X:.2f} m ahead of base_link, "
        f"lens {CAM_Z:.2f} m up, looking down",
        f"  sees {2 * half_x:.2f} m x {2 * half_y:.2f} m of floor, centred on "
        "the reference point",
        f"  capture range for a whole cross: +/-{half_x - 0.04:.2f} m along "
        f"the aisle, +/-{half_y - 0.04:.2f} m across it",
    ])


def default_source() -> Path:
    return (Path(__file__).resolve().parents[3]
            / "src" / "youbot_gazebo" / "urdf" / "youbot_gz.urdf")


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--source", type=Path, default=None)
    ap.add_argument("--target", type=Path,
                    default=Path(__file__).resolve().parents[2]
                    / "urdf" / "youbot_agri.urdf")
    args = ap.parse_args(argv)
    source = args.source or default_source()
    if not source.exists():
        print(f"make_robot: cannot find the Phase B robot at {source}\n"
              "            pass --source explicitly")
        return 1
    print(build(source, args.target))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
