"""make_world -- paint the 48 red crosses into the greenhouse.

The Phase B world (src/youbot_gazebo/worlds/greenhouse.sdf) already has the
building, the gutters, the plants and the aisle floor. This adds the one
thing the new brief needs -- a visible red cross at every measurement station
-- and writes the result to a new file. The source world is never modified,
so the harvesting robot keeps working.

WHY GENERATE RATHER THAN EDIT

Forty-eight crosses is ninety-six boxes. Typed by hand, that is ninety-six
chances to put one at y = -1.75 in the world and -1.70 in the catalogue, and
the robot would then stop 5 cm off a cross for one plant out of forty-eight
with nothing to explain why. Generated from catalogue.py, the two cannot
disagree: there is only one set of numbers.

WHY THE CROSS IS A CROSS AND NOT A DISC

A disc gives the camera a centroid and nothing else. A cross gives two
perpendicular arms, so the same detector recovers the marker's ORIENTATION
as well as its centre -- and orientation is what tells the robot it is
square to the row rather than merely near the right spot. It also survives
partial occlusion better: half a cross is still recognisably a cross, half
a disc is a smaller disc in the wrong place.

The crosses sit at z = 0.004, just above the painted aisle floor (0.001) and
well below anything the lidar sees, so they are visible to the camera and
invisible to the navigation.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

from agri.catalogue import (CROSS_ARM, CROSS_THICKNESS, all_stations,
                            clearances, worst_clearance)

#: Just above the aisle paint, far below the lidar plane.
CROSS_Z = 0.004
#: Bright, fully saturated red with strong emissive so it reads under the
#: greenhouse's own lighting without depending on where the sun is.
CROSS_MATERIAL = """        <material>
            <ambient>0.85 0.05 0.05 1</ambient>
            <diffuse>0.95 0.06 0.06 1</diffuse>
            <specular>0.2 0.02 0.02 1</specular>
            <emissive>0.45 0.02 0.02 1</emissive>
          </material>"""


def cross_sdf(label: str, x: float, y: float) -> str:
    """One station marker: two crossed bars lying on the floor."""
    name = label.replace(",", "_")
    arms = []
    for axis, (sx, sy) in (("x", (2 * CROSS_ARM, CROSS_THICKNESS)),
                           ("y", (CROSS_THICKNESS, 2 * CROSS_ARM))):
        arms.append(f"""      <visual name="{axis}">
          <geometry><box><size>{sx:.4f} {sy:.4f} 0.002</size></box></geometry>
{CROSS_MATERIAL}
        </visual>""")
    return f"""    <!-- station {label} -->
    <model name="cross_{name}">
      <static>true</static>
      <pose>{x:.4f} {y:.4f} {CROSS_Z} 0 0 0</pose>
      <link name="link">
{chr(10).join(arms)}
      </link>
    </model>
"""


def build(source: Path, target: Path) -> tuple[int, str]:
    """Write `source` + the crosses to `target`. Returns (count, report)."""
    sdf = source.read_text()
    if "</world>" not in sdf:
        raise ValueError(f"{source} has no </world> to insert before")
    if "cross_P1_1R" in sdf:
        raise ValueError(f"{source} already contains crosses; generate from "
                         "the ORIGINAL Phase B world, not from a generated one")

    stations = all_stations()
    # NOTE the wording of this banner. A double hyphen is illegal INSIDE an
    # XML comment, and expat reports it as "not well-formed" at a column in
    # a generated file, which points nowhere useful. Phase B lost two
    # debugging sessions to exactly this and carries a regression check for
    # it; the first draft of this generator walked straight into it anyway.
    # So: no "--" between <!-- and -->, and the test suite parses the result.
    block = ("\n    <!-- ================================================\n"
             "         MEASUREMENT STATIONS, generated by\n"
             "         cloud_agri/agri/world/make_world.py from\n"
             "         agri/catalogue.py. Do not edit by hand: the robot\n"
             "         drives to the catalogue's numbers, not to these.\n"
             "         ================================================ -->\n"
             + "".join(cross_sdf(s.label, s.x, s.y) for s in stations))

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(sdf.replace("</world>", block + "  </world>", 1))

    worst, margin = worst_clearance()
    lines = [
        f"{len(stations)} crosses written to {target}",
        f"  arm {CROSS_ARM * 100:.0f} cm, thickness {CROSS_THICKNESS * 100:.1f} cm,"
        f" at z = {CROSS_Z * 1000:.0f} mm",
        f"  tightest station {worst.label}: {margin:.3f} m to the nearest "
        "gutter or wall",
    ]
    pairs = sorted(
        ((a, b, ((a.x - b.x) ** 2 + (a.y - b.y) ** 2) ** 0.5)
         for i, a in enumerate(stations) for b in stations[i + 1:]),
        key=lambda t: t[2])[:1]
    for a, b, d in pairs:
        lines.append(f"  closest pair {a.label} / {b.label}: {d:.3f} m apart "
                     "-- this is what the visual centring has to resolve")
    return len(stations), "\n".join(lines)


def default_source() -> Path:
    """The Phase B world, found relative to this file rather than the cwd."""
    return (Path(__file__).resolve().parents[3]
            / "src" / "youbot_gazebo" / "worlds" / "greenhouse.sdf")


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--source", type=Path, default=None,
                    help="the Phase B greenhouse (default: found automatically)")
    ap.add_argument("--target", type=Path,
                    default=Path(__file__).resolve().parents[2]
                    / "worlds" / "greenhouse_cloud.sdf")
    args = ap.parse_args(argv)

    source = args.source or default_source()
    if not source.exists():
        print(f"make_world: cannot find the source world at {source}\n"
              "            pass --source explicitly")
        return 1
    n, report = build(source, args.target)
    print(report)
    return 0 if n else 1


if __name__ == "__main__":
    raise SystemExit(main())
