"""make_robot -- add the floor camera to the Phase B youbot.

Same rule as make_world.py: read the Phase B robot, write a NEW file, never
touch the original. The harvesting robot keeps its URDF exactly as it was
measured, and this project gets one with a sensor boom on it.

WHAT IS ADDED, AND WHY EACH PIECE

    boom          a bar from the mast out over the front bumper, ending at
                  x = SENSOR_OFFSET_X. This is the point that goes on the
                  cross. It exists as a visual so that what you see in
                  Gazebo is where the robot claims to be.
    floor_cam     a camera at the end of the boom looking straight DOWN.
                  Nadir, so the centre of its picture is the reference point
                  itself -- see agri/vision.py for why that matters and for
                  the sign convention it fixes.

WHY THE SENSOR IS DECLARED ON base_link

sdformat lumps links joined by FIXED joints into their parent, and drops any
sensor attached to a link that gets lumped away. The Phase B URDF carries a
comment about exactly this: its main camera had to move onto the pan head,
which hangs off a REVOLUTE joint and therefore survives. The floor camera has
no reason to move, so rather than invent a joint for it, the sensor is
declared against base_link with an explicit pose. That is the form that
works, and it is the form the original file used before the pan head existed.

WHY NOT JUST EDIT THE URDF BY HAND

Because the camera's height, field of view and forward offset appear in three
places -- the URDF, agri/vision.py's projection, and the driver that turns a
pixel offset into a velocity. Hand-editing means the day someone raises the
boom by 5 cm, two of the three change. Here the URDF is generated FROM
vision.py's constants, so there is one number and it is in Python.
"""

from __future__ import annotations

import argparse
import math
from pathlib import Path

from agri.catalogue import SENSOR_OFFSET_X
from agri.vision import CAM_HFOV, CAM_HEIGHT, CAM_WIDTH, CAM_X, CAM_Y, CAM_Z

#: The gz topic the camera publishes on, and therefore the name the bridge
#: and the robot node must both use. One copy.
FLOOR_CAM_TOPIC = "floor_cam"
BOOM_Z = CAM_Z + 0.07          # the bar rides ABOVE the lens, never in shot


def boom_sdf() -> str:
    """The visible boom and the downward camera, as URDF/gazebo fragments."""
    length = CAM_X - 0.22                      # from the mast to the lens
    mid = 0.22 + length / 2.0
    return f"""
  <!-- ================================================================
       SENSOR BOOM, generated by cloud_agri/agri/world/make_robot.py.
       Do not edit by hand: the numbers come from agri/vision.py and
       agri/catalogue.py, and the robot drives to those, not to these.
       ================================================================ -->
  <link name="sensor_boom">
    <inertial><mass value="0.12"/><inertia ixx="1e-4" ixy="0" ixz="0" iyy="1e-4" iyz="0" izz="1e-4"/></inertial>
    <visual><origin xyz="0 0 0"/><geometry><box size="{length:.4f} 0.035 0.02"/></geometry><material name="dark"/></visual>
  </link>
  <joint name="j_sensor_boom" type="fixed">
    <parent link="base_link"/><child link="sensor_boom"/>
    <origin xyz="{mid:.4f} 0 {BOOM_Z:.4f}"/>
  </joint>

  <link name="floor_cam">
    <inertial><mass value="0.04"/><inertia ixx="1e-5" ixy="0" ixz="0" iyy="1e-5" iyz="0" izz="1e-5"/></inertial>
    <visual><geometry><box size="0.035 0.035 0.03"/></geometry><material name="dark"/></visual>
  </link>
  <joint name="j_floor_cam" type="fixed">
    <parent link="base_link"/><child link="floor_cam"/>
    <origin xyz="{CAM_X:.4f} {CAM_Y:.4f} {CAM_Z:.4f}" rpy="0 {math.pi / 2:.6f} 0"/>
  </joint>
  <gazebo reference="floor_cam"><gravity>false</gravity></gazebo>
  <gazebo reference="sensor_boom"><gravity>false</gravity></gazebo>

  <!-- Declared on base_link with an explicit pose, NOT on floor_cam: a link
       behind a fixed joint is lumped away by sdformat and its sensor goes
       with it. rpy pitch = +pi/2 turns the camera's viewing axis from body
       +x to straight down; agri/vision.py depends on exactly this line. -->
  <gazebo reference="base_link">
    <sensor name="floor_cam" type="camera">
      <pose>{CAM_X:.4f} {CAM_Y:.4f} {CAM_Z:.4f} 0 {math.pi / 2:.6f} 0</pose>
      <topic>{FLOOR_CAM_TOPIC}</topic>
      <update_rate>10</update_rate>
      <always_on>true</always_on>
      <visualize>false</visualize>
      <camera>
        <horizontal_fov>{CAM_HFOV}</horizontal_fov>
        <image>
          <width>{CAM_WIDTH}</width>
          <height>{CAM_HEIGHT}</height>
          <format>R8G8B8</format>
        </image>
        <clip><near>0.02</near><far>3.0</far></clip>
      </camera>
      <gz_frame_id>floor_cam</gz_frame_id>
    </sensor>
  </gazebo>
"""


def build(source: Path, target: Path) -> str:
    urdf = source.read_text()
    if "</robot>" not in urdf:
        raise ValueError(f"{source} has no </robot> to insert before")
    if "floor_cam" in urdf:
        raise ValueError(f"{source} already has the boom; generate from the "
                         "ORIGINAL Phase B robot, not from a generated one")
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(urdf.replace("</robot>", boom_sdf() + "</robot>", 1))

    half_x = CAM_Z * math.tan(CAM_HFOV / 2.0) * CAM_HEIGHT / CAM_WIDTH
    half_y = CAM_Z * math.tan(CAM_HFOV / 2.0)
    return "\n".join([
        f"floor camera written to {target}",
        f"  reference point {SENSOR_OFFSET_X:.2f} m ahead of base_link, "
        f"lens {CAM_Z:.2f} m up, looking down",
        f"  sees {2 * half_x:.2f} m x {2 * half_y:.2f} m of floor, centred on "
        "the reference point",
        f"  capture range for a whole cross: +/-{half_x - 0.04:.2f} m along "
        f"the aisle, +/-{half_y - 0.04:.2f} m across it",
    ])


def default_source() -> Path:
    return (Path(__file__).resolve().parents[3]
            / "src" / "youbot_gazebo" / "urdf" / "youbot_gz.urdf")


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--source", type=Path, default=None)
    ap.add_argument("--target", type=Path,
                    default=Path(__file__).resolve().parents[2]
                    / "urdf" / "youbot_agri.urdf")
    args = ap.parse_args(argv)
    source = args.source or default_source()
    if not source.exists():
        print(f"make_robot: cannot find the Phase B robot at {source}\n"
              "            pass --source explicitly")
        return 1
    print(build(source, args.target))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
